# config/baseline/zimtohrli.yaml
name: zimtohrli
system: zimtohrli
zimtohrli_sample_rate: 48000   # Zimtohrli requires 48kHz audio
batch: 1
n_batches: 1

separator:
  keep_vocals: False # Set to True if you want to keep the separated vocals
  sample_rate: 44100 # sample_rate of the separation model

reference: unprocessed