data:
  cadenza_data_root: /scratch/work/peterr2/baseline_code
  dataset: cadenza_data
  sample_rate: 44100  # Sample rate of the audio files


# Hydra parameters
hydra:
  run:
    dir: exp
  job:
    chdir: True
